title: YANA - Yet Another Node Automator
description: A lightweight Configuration Management and Automation Tool for PowerShell and Bash
remote_theme: just-the-docs/just-the-docs
url: https://oops-42.github.io/yana

nav_sort: order

nav_external_links:
  - title: YANA code and issue tracker
    url: https://github.com/oops-42/yana
    hide_icon: false
    opens_in_new_tab: true
  - title: YANA Modules Repository
    url: https://github.com/oops-42/yana-modules
    hide_icon: false
    opens_in_new_tab: true

plugins:
  - jekyll-remote-theme

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.16.0"
